<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use App\Models\Product;
use App\Models\Sale;
use App\Models\SaleItem;
use App\Models\Payment;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class DummyDataSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();

        // 1. Create Products using the factory
        $products = Product::factory()->count(20)->create();

        // 2. Create Customers
        for ($i = 0; $i < 5; $i++) {
            $customer = Customer::create([
                'name' => $faker->name(),
                'phone' => $faker->phoneNumber(),
                'email' => $faker->safeEmail(),
                'address' => $faker->address(),
                'opening_balance' => 0,
                'due_balance' => 0,
            ]);

            // Add more than 4 sales for each customer (e.g. 5 to 8)
            $salesCount = $faker->numberBetween(5, 8);
            for ($j = 0; $j < $salesCount; $j++) {
                $saleProducts = $faker->randomElements($products->all(), $faker->numberBetween(1, 4));
                
                $subtotal = 0;
                $profit = 0;
                
                $saleItems = [];
                foreach ($saleProducts as $product) {
                    $qty = $faker->numberBetween(1, 3);
                    $itemSubtotal = $product->selling_price * $qty;
                    $itemProfit = ($product->selling_price - $product->cost_price) * $qty;
                    
                    $subtotal += $itemSubtotal;
                    $profit += $itemProfit;
                    
                    $saleItems[] = [
                        'product_id' => $product->id,
                        'quantity' => $qty,
                        'cost_price' => $product->cost_price,
                        'selling_price' => $product->selling_price,
                        'subtotal' => $itemSubtotal,
                    ];
                }
                
                $discount = $faker->randomFloat(2, 0, 10);
                $tax = 0;
                $grandTotal = $subtotal - $discount + $tax;
                $paid = $grandTotal; // marking as paid
                $due = 0;
                
                $sale = Sale::create([
                    'customer_id' => $customer->id,
                    'invoice_no' => 'INV-' . strtoupper(Str::random(8)),
                    'date' => $faker->dateTimeBetween('-6 months', 'now')->format('Y-m-d'),
                    'subtotal_amount' => $subtotal,
                    'discount_amount' => $discount,
                    'tax_amount' => $tax,
                    'grand_total' => $grandTotal,
                    'paid_amount' => $paid,
                    'due_amount' => $due,
                    'payment_status' => 'paid',
                    'profit' => $profit,
                    'notes' => 'Test sale generated by seeder',
                ]);
                
                foreach ($saleItems as $item) {
                    $item['sale_id'] = $sale->id;
                    SaleItem::create($item);
                }
                
                // Create payment
                Payment::create([
                    'paymentable_type' => Sale::class,
                    'paymentable_id' => $sale->id,
                    'amount' => $paid,
                    'payment_method' => 'cash',
                    'date' => $sale->date,
                    'reference' => 'REF-' . strtoupper(Str::random(6)),
                    'party_customer_id' => $customer->id,
                ]);
            }
        }
        
        $this->command->info('Dummy data created successfully! Added 20 Products, 5 Customers, and 5-8 sales per customer.');
    }
}
