<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use App\Models\Product;
use App\Models\Sale;
use App\Models\SaleItem;
use App\Models\Payment;
use Illuminate\Support\Str;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class DummyDataSeeder2 extends Seeder
{
    public function run()
    {
        $faker = Faker::create();

        // 1. Clear existing sales, items, and payments to have exact numbers
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        SaleItem::truncate();
        Sale::truncate();
        Payment::where('paymentable_type', Sale::class)->delete();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Ensure we have enough products
        $productsCount = Product::count();
        if ($productsCount < 10) {
            Product::factory()->count(15)->create();
        }
        $products = Product::all();

        // 2. Iterate through customers and create exact sales
        $customers = Customer::all();

        foreach ($customers as $customer) {
            $salesCount = 4; // default
            
            if (strtolower($customer->name) === 'test') {
                $salesCount = 6;
            } elseif (strtolower($customer->name) === 'stephania gulgowski') {
                $salesCount = 8;
            }

            for ($j = 0; $j < $salesCount; $j++) {
                // Each sale must have more than 5 products (e.g. 6 to 8)
                $numProducts = $faker->numberBetween(6, min(10, $products->count()));
                $saleProducts = $products->random($numProducts);
                
                $subtotal = 0;
                $profit = 0;
                
                $saleItems = [];
                foreach ($saleProducts as $product) {
                    // Each product needs to sell more than 10 qty (e.g. 11 to 20)
                    $qty = $faker->numberBetween(11, 20);
                    $itemSubtotal = $product->selling_price * $qty;
                    $itemProfit = ($product->selling_price - $product->cost_price) * $qty;
                    
                    $subtotal += $itemSubtotal;
                    $profit += $itemProfit;
                    
                    $saleItems[] = [
                        'product_id' => $product->id,
                        'quantity' => $qty,
                        'cost_price' => $product->cost_price,
                        'selling_price' => $product->selling_price,
                        'subtotal' => $itemSubtotal,
                    ];
                }
                
                $discount = $faker->randomFloat(2, 0, 10);
                $tax = 0;
                $grandTotal = $subtotal - $discount + $tax;
                $paid = $grandTotal; // Assuming fully paid
                
                $sale = Sale::create([
                    'customer_id' => $customer->id,
                    'invoice_no' => 'INV-' . strtoupper(Str::random(8)),
                    'date' => $faker->dateTimeBetween('-6 months', 'now')->format('Y-m-d'),
                    'subtotal_amount' => $subtotal,
                    'discount_amount' => $discount,
                    'tax_amount' => $tax,
                    'grand_total' => $grandTotal,
                    'paid_amount' => $paid,
                    'due_amount' => 0,
                    'payment_status' => 'paid',
                    'profit' => $profit,
                    'notes' => 'Test sale generated by specialized seeder',
                ]);
                
                foreach ($saleItems as $item) {
                    $item['sale_id'] = $sale->id;
                    SaleItem::create($item);
                }
                
                // Create payment
                Payment::create([
                    'paymentable_type' => Sale::class,
                    'paymentable_id' => $sale->id,
                    'amount' => $paid,
                    'payment_method' => 'cash',
                    'date' => $sale->date,
                    'reference' => 'REF-' . strtoupper(Str::random(6)),
                    'party_customer_id' => $customer->id,
                ]);
            }
        }
        
        $this->command->info('DummyDataSeeder2 completed successfully!');
    }
}
